# Generated by Django 6.0.1 on 2026-01-20 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('passport_number', models.CharField(blank=True, max_length=50, null=True)),
                ('passport_expiry_date', models.DateField(blank=True, null=True)),
                ('emirates_id_number', models.CharField(blank=True, max_length=50, null=True)),
                ('emirates_id_expiry_date', models.DateField(blank=True, null=True)),
                ('visa_type', models.CharField(choices=[('Employment', 'Employment'), ('Visit', 'Visit'), ('Golden', 'Golden'), ('Investor', 'Investor'), ('Dependent', 'Dependent')], max_length=20)),
                ('visa_expiry_date', models.DateField(blank=True, null=True)),
                ('department', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('employment_status', models.CharField(choices=[('Active', 'Active'), ('On Leave', 'On Leave'), ('Terminated', 'Terminated')], default='Active', max_length=20)),
                ('work_location', models.CharField(max_length=100)),
                ('manager_name', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
